### ISSUE TITLE
ERROR when deploying in CE GA2

### ISSUE THREAD

**Issue by ghost** [rotterdam-cs/liferayGoogleAnalytics-portlet#1]
hi, i tried to hot deploy the portlet but i get errors....im new to this so i am adding error log.

Mar 20, 2013 4:48:06 AM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
04:48:13,588 INFO  [pool-2-thread-1][DialectDetector:71] Determine dialect for MySQL 5
04:48:13,637 INFO  [pool-2-thread-1][DialectDetector:136] Found dialect org.hibernate.dialect.MySQLDialect
Starting Liferay Portal Community Edition 6.1.1 CE GA2 (Paton / Build 6101 / July 31, 2012)
04:48:45,356 INFO  [pool-2-thread-1][BaseDB:455] Database does not support case sensitive queries
04:48:45,928 INFO  [pool-2-thread-1][ServerDetector:154] Server supports hot deploy
04:48:45,941 INFO  [pool-2-thread-1][PluginPackageUtil:1030] Reading plugin package for the root context
04:48:55,390 INFO  [pool-2-thread-1][AutoDeployDir:106] Auto deploy scanner started for D:\lr\liferay-portal-6.1.1-ce-ga2\deploy
04:48:58,311 INFO  [pool-2-thread-1][HotDeployImpl:178] Deploying doc_pagin-portlet from queue
04:48:58,314 INFO  [pool-2-thread-1][PluginPackageUtil:1033] Reading plugin package for doc_pagin-portlet
Loading file:/D:/lr/liferay-portal-6.1.1-ce-ga2/tomcat-7.0.27/webapps/doc_pagin-portlet/WEB-INF/classes/portlet.properties
Loading file:/D:/lr/liferay-portal-6.1.1-ce-ga2/tomcat-7.0.27/webapps/doc_pagin-portlet/WEB-INF/classes/service.properties
Mar 20, 2013 4:48:58 AM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
Loading file:/D:/lr/liferay-portal-6.1.1-ce-ga2/tomcat-7.0.27/webapps/doc_pagin-portlet/WEB-INF/classes/portlet.properties
Loading file:/D:/lr/liferay-portal-6.1.1-ce-ga2/tomcat-7.0.27/webapps/doc_pagin-portlet/WEB-INF/classes/service.properties
Loading file:/D:/lr/liferay-portal-6.1.1-ce-ga2/tomcat-7.0.27/webapps/doc_pagin-portlet/WEB-INF/classes/service.properties
04:48:59,236 INFO  [pool-2-thread-1][HookHotDeployListener:550] Registering hook for doc_pagin-portlet
04:48:59,283 INFO  [pool-2-thread-1][HookHotDeployListener:690] Hook for doc_pagin-portlet is available for use
Loading file:/D:/lr/liferay-portal-6.1.1-ce-ga2/tomcat-7.0.27/webapps/doc_pagin-portlet/WEB-INF/classes/portlet.properties
Mar 20, 2013 4:49:01 AM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring FrameworkServlet 'Remoting Servlet'
04:49:05,404 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:177] Processing rcs-liferay-google-analytics-portlet-6.1.1.0.war
04:49:05,420 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][PortletAutoDeployListener:77] Copying portlets for D:\lr\liferay-portal-6.1.1-ce-ga2\deploy\rcs-liferay-google-analytics-portlet-6.1.1.0.war
04:49:05,424 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][BaseDeployer:763] Deploying rcs-liferay-google-analytics-portlet-6.1.1.0.war
04:49:05,430 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][BaseDeployer:859] Updating Liferay Google Analytics from version 6.1.1.0 to version 6.1.1.0
Mar 20, 2013 4:49:05 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory D:\lr\liferay-portal-6.1.1-ce-ga2\tomcat-7.0.27\webapps\marketplace-portlet
  Expanding: D:\lr\liferay-portal-6.1.1-ce-ga2\deploy\rcs-liferay-google-analytics-portlet-6.1.1.0.war into D:\lr\liferay-portal-6.1.1-ce-ga2\tomcat-7.0.27\temp\20130320044905433
04:49:07,956 INFO  [pool-2-thread-1][HotDeployImpl:178] Deploying marketplace-portlet from queue
04:49:07,965 INFO  [pool-2-thread-1][PluginPackageUtil:1033] Reading plugin package for marketplace-portlet
Loading file:/D:/lr/liferay-portal-6.1.1-ce-ga2/tomcat-7.0.27/temp/0-marketplace-portlet/WEB-INF/classes/portlet.properties
Loading file:/D:/lr/liferay-portal-6.1.1-ce-ga2/tomcat-7.0.27/temp/0-marketplace-portlet/WEB-INF/classes/service.properties
Mar 20, 2013 4:49:08 AM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
Loading file:/D:/lr/liferay-portal-6.1.1-ce-ga2/tomcat-7.0.27/temp/0-marketplace-portlet/WEB-INF/classes/portlet.properties
Loading file:/D:/lr/liferay-portal-6.1.1-ce-ga2/tomcat-7.0.27/temp/0-marketplace-portlet/WEB-INF/classes/service.properties
Loading file:/D:/lr/liferay-portal-6.1.1-ce-ga2/tomcat-7.0.27/temp/0-marketplace-portlet/WEB-INF/classes/service.properties
04:49:08,707 INFO  [pool-2-thread-1][HookHotDeployListener:550] Registering hook for marketplace-portlet
Loading file:/D:/lr/liferay-portal-6.1.1-ce-ga2/tomcat-7.0.27/temp/0-marketplace-portlet/WEB-INF/classes/portal.properties
04:49:09,039 INFO  [pool-2-thread-1][HookHotDeployListener:690] Hook for marketplace-portlet is available for use
Loading file:/D:/lr/liferay-portal-6.1.1-ce-ga2/tomcat-7.0.27/temp/0-marketplace-portlet/WEB-INF/classes/portlet.properties
Mar 20, 2013 4:49:09 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory D:\lr\liferay-portal-6.1.1-ce-ga2\tomcat-7.0.27\webapps\rcs-liferay-google-analytics-portlet
Mar 20, 2013 4:49:20 AM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rcs-liferay-google-analytics-portlet]]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:895)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:871)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:615)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1099)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1621)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.IllegalArgumentException: Filter mapping specifies an unknown filter name OpenSessionInViewFilter
    at org.apache.catalina.core.StandardContext.validateFilterMap(StandardContext.java:3003)
    at org.apache.catalina.core.StandardContext.addFilterMap(StandardContext.java:2968)
    at org.apache.catalina.deploy.WebXml.configureContext(WebXml.java:1207)
    at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1357)
    at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:855)
    at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:345)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5161)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    ... 11 more
Mar 20, 2013 4:49:20 AM org.apache.catalina.startup.HostConfig deployDirectory
SEVERE: Error deploying web application directory D:\lr\liferay-portal-6.1.1-ce-ga2\tomcat-7.0.27\webapps\rcs-liferay-google-analytics-portlet
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rcs-liferay-google-analytics-portlet]]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:898)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:871)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:615)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1099)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1621)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:619)
Mar 20, 2013 4:49:20 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory D:\lr\liferay-portal-6.1.1-ce-ga2\tomcat-7.0.27\webapps\resources-importer-web
04:49:21,437 INFO  [pool-2-thread-1][HotDeployImpl:178] Deploying resources-importer-web from queue
04:49:21,437 INFO  [pool-2-thread-1][PluginPackageUtil:1033] Reading plugin package for resources-importer-web
Mar 20, 2013 4:49:21 AM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
Mar 20, 2013 4:49:21 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory D:\lr\liferay-portal-6.1.1-ce-ga2\tomcat-7.0.27\webapps\welcome-theme
INFO: Deploying web application directory D:\lr\liferay-portal-6.1.1-ce-ga2\tomcat-7.0.27\webapps\rcs-liferay-google-analytics-portlet
Mar 20, 2013 4:49:40 AM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rcs-liferay-google-analytics-portlet]]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:895)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:871)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:615)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1099)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1621)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.IllegalArgumentException: Filter mapping specifies an unknown filter name OpenSessionInViewFilter
    at org.apache.catalina.core.StandardContext.validateFilterMap(StandardContext.java:3003)
    at org.apache.catalina.core.StandardContext.addFilterMap(StandardContext.java:2968)
    at org.apache.catalina.deploy.WebXml.configureContext(WebXml.java:1207)
    at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1357)
    at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:855)
    at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:345)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5161)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    ... 11 more
Mar 20, 2013 4:49:40 AM org.apache.catalina.startup.HostConfig deployDirectory
SEVERE: Error deploying web application directory D:\lr\liferay-portal-6.1.1-ce-ga2\tomcat-7.0.27\webapps\rcs-liferay-google-analytics-portlet
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rcs-liferay-google-analytics-portlet]]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:898)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:871)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:615)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1099)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1621)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:619)
  Copying 1 file to D:\lr\liferay-portal-6.1.1-ce-ga2\tomcat-7.0.27\webapps\rcs-liferay-google-analytics-portlet
  Deleting directory D:\lr\liferay-portal-6.1.1-ce-ga2\tomcat-7.0.27\temp\20130320044905433
04:49:41,816 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][PortletAutoDeployListener:87] Portlets for D:\lr\liferay-portal-6.1.1-ce-ga2\deploy\rcs-liferay-google-analytics-portlet-6.1.1.0.war copied successfully. Deployment will start in a few seconds.
Mar 20, 2013 4:49:50 AM org.apache.catalina.startup.HostConfig checkResources
INFO: Reloading context [/rcs-liferay-google-analytics-portlet]
Mar 20, 2013 4:49:53 AM org.apache.catalina.startup.HostConfig checkResources
WARNING: Error during context [/rcs-liferay-google-analytics-portlet] restart
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rcs-liferay-google-analytics-portlet]]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
    at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1366)
    at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1454)
    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:295)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
    at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1379)
    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1537)
    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1547)
    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1526)
    at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.IllegalArgumentException: Filter mapping specifies an unknown filter name OpenSessionInViewFilter
    at org.apache.catalina.core.StandardContext.validateFilterMap(StandardContext.java:3003)
    at org.apache.catalina.core.StandardContext.addFilterMap(StandardContext.java:2968)
    at org.apache.catalina.deploy.WebXml.configureContext(WebXml.java:1207)
    at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1357)
    at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:855)
    at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:345)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5161)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    ... 10 more

**Comment by ghost** [comment]
IThink the .war file on rcs website is out dated. imported source from git hub using egit plugin for eclpse. now working.
